import { zipSync, strToU8 } from "fflate";

// Maps our loader id to the dependency key used inside modrinth.index.json.
const LOADER_KEY = {
  fabric: "fabric-loader",
  quilt: "quilt-loader",
  forge: "forge",
  neoforge: "neoforge",
};

// Best-effort lookup of the latest loader version. Runs in the browser, so any
// domain is reachable. Always resolves (empty string on failure) — never throws.
async function getLoaderVersion(loader, mc) {
  try {
    if (loader === "fabric") {
      const d = await (await fetch("https://meta.fabricmc.net/v2/versions/loader")).json();
      const s = d.find((x) => x.stable) || d[0];
      return s ? s.version : "";
    }
    if (loader === "quilt") {
      const d = await (await fetch("https://meta.quiltmc.org/v3/versions/loader")).json();
      return d[0] ? d[0].version : "";
    }
    if (loader === "neoforge") {
      const t = await (
        await fetch(
          "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml"
        )
      ).text();
      const all = [...t.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
      const p = mc.split(".");
      const prefix = `${p[1]}.${p[2] || "0"}.`;
      const matches = all.filter((v) => v.startsWith(prefix) && !v.includes("beta"));
      return matches[matches.length - 1] || all[all.length - 1] || "";
    }
    if (loader === "forge") {
      const t = await (
        await fetch(
          "https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml"
        )
      ).text();
      const all = [...t.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
      const matches = all.filter((v) => v.startsWith(`${mc}-`));
      const latest = matches[matches.length - 1] || "";
      return latest ? latest.slice(`${mc}-`.length) : "";
    }
  } catch {
    // fall through to empty
  }
  return "";
}

// Map Modrinth's *project* attributes to mrpack's *install instruction*.
//
// These two look alike but mean different things. `client_side: "optional"` on a
// project means "works without being required"; copying that straight into the
// mrpack index tells the launcher the mod is optional *for this pack*, and
// launchers may then skip it. The pack we generate is a list of mods the user
// chose to install, so anything that CAN run in an environment is "required"
// there; only a genuinely unsupported side stays "unsupported".
function envFor(mod) {
  return {
    client: mod.client_side === "unsupported" ? "unsupported" : "required",
    server: mod.server_side === "unsupported" ? "unsupported" : "required",
  };
}

// A file name that survives Windows/macOS and still says what the pack is.
function safeFileName(packName) {
  const base = packName
    .replace(/[\\/:*?"<>|]+/g, "-")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^[_-]+|[_-]+$/g, "");
  return `${base || "modpack"}.mrpack`;
}

// Build a .mrpack (Modrinth modpack) Blob from a built pack object.
// Returns { blob, name, included, skipped, loaderMissing }.
export async function buildMrpack(pack, packName) {
  const mods = pack.categories.flatMap((c) => c.mods);
  const withFile = mods.filter((m) => m.file && m.file.url && m.file.filename);
  const skipped = mods.length - withFile.length;

  const files = withFile.map((m) => ({
    path: `mods/${m.file.filename}`,
    hashes: { sha1: m.file.sha1 || "", sha512: m.file.sha512 || "" },
    env: envFor(m),
    downloads: [m.file.url],
    fileSize: m.file.size || 0,
  }));

  // Mods that cannot run on a client at all: the launcher will not install them
  // on a client instance, so the UI must not claim they were included.
  const clientUnsupported = withFile.filter(
    (m) => m.client_side === "unsupported"
  ).length;
  const totalSize = files.reduce((n, f) => n + (f.fileSize || 0), 0);

  const loaderVersion = await getLoaderVersion(pack.loader, pack.version);
  const dependencies = { minecraft: pack.version };
  const key = LOADER_KEY[pack.loader];
  if (key) dependencies[key] = loaderVersion;

  const index = {
    formatVersion: 1,
    game: "minecraft",
    versionId: "1.0.0",
    name: packName || "MOD PACK FINDER pack",
    summary: "Generated by MOD PACK FINDER",
    files,
    dependencies,
  };

  const json = JSON.stringify(index, null, 2);
  const zipped = zipSync(
    { "modrinth.index.json": strToU8(json) },
    { level: 6 }
  );
  const blob = new Blob([zipped], { type: "application/x-modrinth-modpack+zip" });

  return {
    blob,
    name: safeFileName(packName || "modpack"),
    included: files.length,
    skipped,
    clientUnsupported,
    totalSize,
    loaderMissing: !loaderVersion,
  };
}

// Trigger a browser download for a Blob.
export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
