import { zipSync, strToU8 } from "fflate";

// Maps our loader id to the dependency key used inside modrinth.index.json.
const LOADER_KEY = {
  fabric: "fabric-loader",
  quilt: "quilt-loader",
  forge: "forge",
  neoforge: "neoforge",
};

// Best-effort lookup of the latest loader version. Runs in the browser, so any
// domain is reachable. Always resolves (empty string on failure) — never throws.
async function getLoaderVersion(loader, mc) {
  try {
    if (loader === "fabric") {
      const d = await (await fetch("https://meta.fabricmc.net/v2/versions/loader")).json();
      const s = d.find((x) => x.stable) || d[0];
      return s ? s.version : "";
    }
    if (loader === "quilt") {
      const d = await (await fetch("https://meta.quiltmc.org/v3/versions/loader")).json();
      return d[0] ? d[0].version : "";
    }
    if (loader === "neoforge") {
      const t = await (
        await fetch(
          "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml"
        )
      ).text();
      const all = [...t.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
      const p = mc.split(".");
      const prefix = `${p[1]}.${p[2] || "0"}.`;
      const matches = all.filter((v) => v.startsWith(prefix) && !v.includes("beta"));
      return matches[matches.length - 1] || all[all.length - 1] || "";
    }
    if (loader === "forge") {
      const t = await (
        await fetch(
          "https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml"
        )
      ).text();
      const all = [...t.matchAll(/<version>([^<]+)<\/version>/g)].map((m) => m[1]);
      const matches = all.filter((v) => v.startsWith(`${mc}-`));
      const latest = matches[matches.length - 1] || "";
      return latest ? latest.slice(`${mc}-`.length) : "";
    }
  } catch {
    // fall through to empty
  }
  return "";
}

function envValue(v) {
  return v === "optional" || v === "unsupported" ? v : "required";
}

// Build a .mrpack (Modrinth modpack) Blob from a built pack object.
// Returns { blob, name, included, skipped, loaderMissing }.
export async function buildMrpack(pack, packName) {
  const mods = pack.categories.flatMap((c) => c.mods);
  const withFile = mods.filter((m) => m.file && m.file.url && m.file.filename);
  const skipped = mods.length - withFile.length;

  const files = withFile.map((m) => ({
    path: `mods/${m.file.filename}`,
    hashes: { sha1: m.file.sha1 || "", sha512: m.file.sha512 || "" },
    env: { client: envValue(m.client_side), server: envValue(m.server_side) },
    downloads: [m.file.url],
    fileSize: m.file.size || 0,
  }));

  const loaderVersion = await getLoaderVersion(pack.loader, pack.version);
  const dependencies = { minecraft: pack.version };
  const key = LOADER_KEY[pack.loader];
  if (key) dependencies[key] = loaderVersion;

  const index = {
    formatVersion: 1,
    game: "minecraft",
    versionId: "1.0.0",
    name: packName || "MOD PACK FINDER pack",
    summary: "Generated by MOD PACK FINDER",
    files,
    dependencies,
  };

  const json = JSON.stringify(index, null, 2);
  const zipped = zipSync(
    { "modrinth.index.json": strToU8(json) },
    { level: 6 }
  );
  const blob = new Blob([zipped], { type: "application/x-modrinth-modpack+zip" });

  return {
    blob,
    name: `${(packName || "modpack").replace(/[^\w.-]+/g, "_")}.mrpack`,
    included: files.length,
    skipped,
    loaderMissing: !loaderVersion,
  };
}

// Trigger a browser download for a Blob.
export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
